### ISSUE TITLE
creating landing page for website

### ISSUE THREAD

**Issue by nikim178** [Aman1-coder/GameSphere#1]
@Aman1-coder I'm interested in working on it. May I have permission to tackle this issue?

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by Thrillseekr** [comment]
Hey @Aman1-coder, 
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in HTML5, CSS, PHP, Bootstrap, and creativity too. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by Aman1-coder** [comment]
Hello @nikim178 @praharshaAdhikari @rahultomarr @Thrillseekr You have seen the Design of home page https://snowflaketest.my.canva.site/gamesphere you are able to modify little bit but you can't change whole design

**Comment by kdotambuj** [comment]
Can you assign it to me? I have seen the design of home page, I will modify according to the instructions.

**Comment by Aman1-coder** [comment]
@kdotambuj Sure, Please could you tell me how much time taken you be able to send PR

**Comment by kdotambuj** [comment]
@Aman1-coder 3-4 days

**Comment by arcVaishali** [comment]
Hello **@Aman1-coder** I have created many **landing pages** using front-end web tools like **HTML** and **CSS**, I am interested in tackling the issue. Kindly assign me this issue.

**Comment by Aman1-coder** [comment]
@kdotambuj You need and partner for landing page or you are individually able to complete

**Comment by Aman1-coder** [comment]
@arcVaishali you have seen the design are able to build that project

**Comment by kdotambuj** [comment]
@Aman1-coder I can make it individually, but it would be better to work with a partner.

**Comment by Aman1-coder** [comment]
ok i'll find some more persons

**Comment by Thrillseekr** [comment]
@Aman1-coder 
I'll ready to work with @kdotambuj

**Comment by Pragati-3003** [comment]
Hey, 
I would like to contribute in this under GSSOC'23. 
Please assign this to me.

**Comment by Aman1-coder** [comment]
@Thrillseekr Nice now can i assign both of you or find more contributor

**Comment by kdotambuj** [comment]
@Aman1-coder yeah you can assign us

**Comment by arcVaishali** [comment]
> @arcVaishali you have seen the design are able to build that project 

Yes, **@Aman1-coder** I have seen I can make.

**Comment by arcVaishali** [comment]
> @Aman1-coder I can make it individually, but it would be better to work with a partner.

Hey! **@kdotambuj** I am interested in working with you in tackling the issue.

**Comment by kdotambuj** [comment]
@Aman1-coder you can assign her as well @arcVaishali

**Comment by Thrillseekr** [comment]
So, now we are 3 to work upon the same

**Comment by Aman1-coder** [comment]
yes there are three members i'll been selected @kdotambuj @Thrillseekr @arcVaishali

**Comment by Aman1-coder** [comment]
Are you ready to start work

**Comment by arcVaishali** [comment]
> So, now we are 3 to work upon the same

Yes, if **@Aman1-coder** assigns us.

**Comment by Aman1-coder** [comment]
Ok Nice

**Comment by arcVaishali** [comment]
> Are you ready to start work

Sure **@Aman1-coder** I am excited.

**Comment by Aman1-coder** [comment]
Now can i create any group for talk

**Comment by Aman1-coder** [comment]
As all members are agree

**Comment by Thrillseekr** [comment]
Yes, super excited

**Comment by arcVaishali** [comment]
**@Aman1-coder** Yes sure!

**Comment by kdotambuj** [comment]
yeah sure @Aman1-coder

**Comment by Aman1-coder** [comment]
Where can i create group telegram or any other platform please suggest

**Comment by Aman1-coder** [comment]
i'll created on Discord https://discord.gg/aSGgBRp6

**Comment by arcVaishali** [comment]
Great

**Comment by nikim178** [comment]
@Aman1-coder hey i also want to work on the landing page. Can u please assign to me and i will work with @kdotambuj @arcVaishali @Thrillseekr

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23

**Comment by Tushar98644** [comment]
I would like to contribute in developing the homepage if there are any vacancies left @Aman1-coder

**Comment by AnushkaGupta2003** [comment]
@Aman1-coder Can I work on the landing page and make more improvements after the landing page is created by the assigned contributors?
I have good knowledge of Bootstrap, CSS, HTML and have made projects where I have applied the same

**Comment by AK4266** [comment]
Hey, can i work on this issue?
