### ISSUE TITLE
add tic tac toe game

### ISSUE THREAD

**Issue by S-ishita** [Aman1-coder/GameSphere#10]
I want to add tic tac toe game which can later be integrated with landing page.Please assign this issue to me under GSSOC

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contibutor.

**Comment by Srideepthi2384** [comment]
I wanna contribute this project.. So plz assign me

**Comment by Aman1-coder** [comment]
@Aditi323 @Srideepthi2384 @S-ishita we are currently work on home page so please wait
