### ISSUE TITLE
[New game]: Maze Game

### ISSUE THREAD

**Issue by Pragati-3003** [Aman1-coder/GameSphere#108]
### 🎮 Game Request

I am writing to request the addition of my Maze Game project. 
![maze_game](https://github.com/Aman1-coder/GameSphere/assets/132778037/fbb45270-eaba-4b31-82a0-7b0de166f435)

### Point down the features

The game features various levels of difficulty, visually appealing graphics, and an intuitive user interface.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@Pragati-3003 Could you please explain this is single player or multiplayer game , if single player then try to create some  multiplayer games then I'll assign you

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Could you please explain this is single player or multiplayer game , if it is single player then try to create some multiplayer games then I'll assign you

This is completely single player game and can't be converted in the multi player game.
