### ISSUE TITLE
[New game]: Smash Cube game

### ISSUE THREAD

**Issue by Pragati-3003** [Aman1-coder/GameSphere#109]
### 🎮 Game Request

I would like to add the smash cube game to the repository.
![smash_cube](https://github.com/Aman1-coder/GameSphere/assets/132778037/aadd5142-5d98-43e5-8930-60845bb13172)

so,please assign this to me.

### Point down the features

This is a game where you have to smash the cubes moving on the screen and earn points.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@Pragati-3003 Could you please explain this is single player or multiplayer game , if it is  single player then try to create some  multiplayer games then I'll assign you

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Could you please explain this is single player or multiplayer game , if it is single player then try to create some multiplayer games then I'll assign you

This is completely single player game and can't be converted in the multi player game.
