### ISSUE TITLE
[New game]: Bubble Blast Game

### ISSUE THREAD

**Issue by md-rosh02** [Aman1-coder/GameSphere#111]
### 🎮 Game Request

Game Logic:
Bubble Blast is a puzzle game where the objective is to clear the screen of colored bubbles by strategically popping them. The game is played on a grid-based layout, and each bubble has a specific color. When a bubble is popped, it triggers a chain reaction that can cause neighboring bubbles to pop as well.

Basic Description:
Bubble Blast is a visually appealing and addictive puzzle game that challenges players to think strategically. The game features colorful bubbles arranged on a grid, and the player's task is to eliminate all the bubbles from the screen.

### Point down the features

Grid-Based Gameplay: The game is played on a grid, where bubbles of different colors are arranged.

Colorful Bubbles: Each bubble has a specific color, adding visual appeal to the game.

Chain Reactions: Popping a bubble triggers a chain reaction that can cause neighboring bubbles of the same color to pop as well, allowing for efficient clearing of the screen.

Strategic Thinking: Players need to plan their moves carefully to create the largest chain reactions and clear the screen efficiently.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by md-rosh02** [comment]
@Aman1-coder  plz assign me this issue i have done this project if you want you can see
![Bubble_Blast_Game](https://github.com/Aman1-coder/GameSphere/assets/132879891/c84d141b-f762-4cc6-98d7-ccd03361e2a5)

**Comment by Aman1-coder** [comment]
@md-rosh02 this game is fine but if you are able to create a multi player game that would be more interesting. In that case ill assign you.

**Comment by md-rosh02** [comment]
another game or this game

**Comment by Durgesh4993** [comment]
@md-rosh02 are you able to create this game into multiplayer

**Comment by md-rosh02** [comment]
no, it is not possible to create into multiplayer game but i can make another multiplayer game

**Comment by Durgesh4993** [comment]
@md-rosh02 Ok, create new issue

**Comment by md-rosh02** [comment]
ok bhai

**Comment by md-rosh02** [comment]
Sorry, It consume more time
