### ISSUE TITLE
Multiplayer Rock-Paper-Scissors game

### ISSUE THREAD

**Issue by Enhancer18** [Aman1-coder/GameSphere#117]
### 🎮 Game Request

Game logic and basic description
You can actually play this game with your friends. Made using NodeJS + JS + Socket.IO

### Point down the features

Game points

### Select The Game Type

Multiplayer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Enhancer18 This game is already merged try to creat some unique game.
