### ISSUE TITLE
Contact Us Page, FeedBack form and footer

### ISSUE THREAD

**Issue by Vaibhav-Bothra** [Aman1-coder/GameSphere#17]
We can also add feedback form to get the feedbacks from the users and improvise the user experience. I can make feedback form, contact us and footer with impressive user interface and responsive design. Can you assign this to me so that I can work on it as soon as possible as I want to contribute to the project and GSSOC'23?

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me, I will contribute to this issue under GSSoC'23. I can solve this issue with the help of CSS and JavaScript

**Comment by AnushkaGupta2003** [comment]
We can work together with a partner on the issue to resolve it quickly @Aman1-coder
