### ISSUE TITLE
Home Page for Game Sphere

### ISSUE THREAD

**Issue by Thrillseekr** [Aman1-coder/GameSphere#2]
Hey @Aman1-coder,
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in HTML5, CSS, PHP, Bootstrap, and creative designs too. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by Amitdahiya08** [comment]
Dear @Aman1-coder,

I hope this message finds you well. My name is Amit Dahiya, and I am thrilled to be a part of GSSOC'23. I wanted to reach out and express my excitement for this event, as well as my keen interest in contributing to your open source project.

I have a strong background in HTML, CSS, JavaScript, and Bootstrap. These technologies have been my focus  and I have gained significant experience in web development using these tools.
I would greatly appreciate it if you could assign me this project that aligns with my skills and interests. I am particularly interested in working on frontend development tasks, creating responsive and visually appealing user interfaces,

**Comment by Anikinee** [comment]
I would like to work on this issue, please assign it to me under GSSoC'23.

**Comment by Aman1-coder** [comment]
Hello @Amitdahiya08 @Thrillseekr You have seen the Design of home page  https://snowflaketest.my.canva.site/gamesphere you are able to modify little bit but you can't change whole designe

**Comment by Thrillseekr** [comment]
Ok. I'm ready to implement this.
You can assign this to me

**Comment by Aman1-coder** [comment]
@Thrillseekr are you want to create individually or want a partner for Completing the Home page

**Comment by Pragati-3003** [comment]
Heyy  , 
I would like to contribute in this under GSSOC'23. 
Please assign this to me.

**Comment by Thrillseekr** [comment]
> @Thrillseekr are you want to create individually or want a partner for Completing the Home page

I'm ready to work with someone.

**Comment by Amitdahiya08** [comment]
@Thrillseekr we can do it together if you are okay 
@Aman1-coder assign it to both of us please we would love to work on it in team
