### ISSUE TITLE
Adding hangman game!

### ISSUE THREAD

**Issue by anan262** [Aman1-coder/GameSphere#21]
I would like to contribute to this one as I'm super thrilled to work on the same for GSSOC and have immense experience working on websites too!

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create a mind-blowing memory game with pretty amazing UI with the help of CSS and JavaScript

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create a mind-blowing hanging game with pretty amazing UI with the help of CSS and JavaScript
