### ISSUE TITLE
Add playable piano

### ISSUE THREAD

**Issue by DhairyaMajmudar** [Aman1-coder/GameSphere#24]
We can add a playable piano game making it interactive using HTML, CSS and JS

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me

**Comment by Charu-2718** [comment]
Can you please assign me this issue?

**Comment by Aman1-coder** [comment]
@Charu-2718 @DhairyaMajmudar If you are able to create a multiplayer game then create a new issue I'll assign you

**Comment by DhairyaMajmudar** [comment]
Sir @Aman1-coder I can create a multiplayer snake game using js and socket.io
