### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Sriparno08** [Aman1-coder/GameSphere#34]
I want to create CODE_OF_CONDUCT.md for this repository.

This contribution is part of GSSoC'23.

**Comment by Aman1-coder** [comment]
@Sriparno08 ok

**Comment by Durgesh4993** [comment]
@Sriparno08 If you need any help ask to me, because i am mentor of this repository
Connect with me
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Sriparno08** [comment]
Sure 👍
