### ISSUE TITLE
New Game : Minesweeper

### ISSUE THREAD

**Issue by pearlrathour** [Aman1-coder/GameSphere#37]
Please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create it with the help of HTML, CSS, JS

**Comment by Aman1-coder** [comment]
@pearlrathour can you elaborate more what type of game it is. if it`s  multiplayer game it would be more interesting.

**Comment by pearlrathour** [comment]
This is a single player game. Objective of game is to uncover grid squares while avoiding mines. The game is won when all non-mine squares are revealed.
