### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Aman1-coder/GameSphere#4]
I want to add readme badges. please assign this issue to me under GSSOC

**Comment by Aman1-coder** [comment]
@S-ishita Can you please elaborate more

**Comment by S-ishita** [comment]
Similar badges will be added

![badges](https://github.com/Aman1-coder/GameSphere/assets/104543751/e80c8469-54fa-4368-93c4-470b05e69d71)

**Comment by Aman1-coder** [comment]
Ok i'll assigned you
