### ISSUE TITLE
New Game: Ping Pong Game

### ISSUE THREAD

**Issue by Vaibhav-Bothra** [Aman1-coder/GameSphere#50]
I want to add this game to this project. It is an interesting game. I am an enthusiast of Web Development. May you assign this to me so that I can work as soon as possible and contribute to this project and GSSOC'23?

**Comment by Aman1-coder** [comment]
@Vaibhav-Bothra  If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Vaibhav-Bothra** [comment]
Thank you sir for assigning me, if I need any help, I will ask the mentor.
