### ISSUE TITLE
New Game: To create a Rock, Paper, Scissors game 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [Aman1-coder/GameSphere#52]
To create a Rock, Paper, Scissors game with the help of JavaScript and making it attractive with the help of HTML and CSS.

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me I will be solving this issue under GSSoC'23.I will make this game with good-looking visuals with the help of CSS and make it functional with the help of JavaScript

**Comment by DhairyaMajmudar** [comment]
Sir I can complete this issue in only one day it will be great if you assign me this issue.

**Comment by Aman1-coder** [comment]
Ok

**Comment by DhairyaMajmudar** [comment]
Thank You Sir
