### ISSUE TITLE
[New game]: tic tac toe

### ISSUE THREAD

**Issue by Biswajit-Behera** [Aman1-coder/GameSphere#59]
### 🎮 Game Request

Game logic and basic description:- with the help of HTML, CSS and Vanila CSS will create a Tic Tac Toe game. 

### Point down the features

Game points
1 vs 1 or Bot vs 1

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Charu-2718** [comment]
I want to work on this issue as a contributor under GSSoC23, can you please assign me this issue?

**Comment by Biswajit-Behera** [comment]
> I want to work on this issue as a contributor under GSSoC23, can you please assign me this issue?

Currently I am working on this feature/issue.
