### ISSUE TITLE
Add a login and resgister form with validation 

### ISSUE THREAD

**Issue by Geeta259** [Aman1-coder/GameSphere#7]
I would like to contribute in this project under GSSOC'23 . I have decent  knowledge of web development.  
I want to add a SignIn and SignUp form with JS validation .
@Aman1-coder please assign this to me !

**Comment by Aman1-coder** [comment]
@Geeta259 Our first priority to create a home page for website so please wait sometime

**Comment by Geeta259** [comment]
@Aman1-coder  I can contribute in to home page section too by creating a responsive banner for home page and responsive cards to add some games in to .

**Comment by Aman1-coder** [comment]
@Geeta259  Currently we are working on a particular design, But don't worry when home page is completed then i'll personally invite for contributing

**Comment by Aman1-coder** [comment]
we are working on this design https://snowflaketest.my.canva.site/gamesphere are you interested

**Comment by Pragati-3003** [comment]
Hey @Aman1-coder
I would like to contribute in this under GSSOC'23. 
Please assign this to me.

**Comment by Aman1-coder** [comment]
you can see the designe

**Comment by Geeta259** [comment]
> we are working on this design https://snowflaketest.my.canva.site/gamesphere are you interested

Yes I'm interested to work on it !

**Comment by Geeta259** [comment]
Want to create a banner section for a homepage and a card section.
