### ISSUE TITLE
adding the snake and ball game 

### ISSUE THREAD

**Issue by mridulsaggi** [Aman1-coder/GameSphere#78]
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: i would like to add a new game which is ball and snake game the favorite game of our childhood

### Describe the solution you'd like

Solution steps: snake and ball game can be added

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@mridulsaggi Can you explain it is multiplayer game or not, if not so please try to create a multiplayer game I'll assign you

**Comment by Aman1-coder** [comment]
@mridulsaggi If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993
