### ISSUE TITLE
[New game]: chess

### ISSUE THREAD

**Issue by Enhancer18** [Aman1-coder/GameSphere#83]
### 🎮 Game Request

Game logic and basic description
when clicking on a particular piece of the chessboard, It shows you all the possible routes that a particular piece can take and later moves the pieces. it also prevents selecting multiple elements.
If black or white wins the game then the alert appears saying black wins!!.

### Point down the features

Game points
gives who wins or loses

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@Enhancer18 Can you explain it is multiplayer game or not, if not so please try to create a multiplayer game I'll assign you 
If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993

**Comment by Enhancer18** [comment]
> @Enhancer18 Can you explain it is multiplayer game or not, if not so please try to create a multiplayer game I'll assign you 
> If you need any help ask to mentor?
> Connect with mentor:
> LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
> GitHub : https://github.com/Durgesh4993

Yes it is a multiplayer chess game

**Comment by Enhancer18** [comment]
can u assign this @Aman1-coder

**Comment by Aman1-coder** [comment]
sorry @Enhancer18 this game is already assigned to someone else could you please create some new issue I'll assign you
