### ISSUE TITLE
[New game]: Snake Game

### ISSUE THREAD

**Issue by nikhilkumar50** [Aman1-coder/GameSphere#89]
### 🎮 Game Request

Game logic and basic description
Snake is a timeless arcade game where the player controls a snake moving in a grid-based playing area. The objective is to guide the snake to eat food, growing its length while avoiding collisions with walls or its own body. The snake moves in cardinal directions, and as it consumes food, the challenge increases due to its growing size. The game ends if the snake crashes into a wall or itself. 

@Aman1-coder Please assign this project to me under GSSoC'23.

### Point down the features

Game points
Food: The game provides food items scattered throughout the playing area that the snake must eat to grow longer and increase its score.

Increasing Difficulty: As the game progresses, the snake becomes longer, making it more challenging to navigate without colliding with itself or the boundaries.

Score Tracking: The game keeps track of the player's score, usually based on the number of food items consumed or the snake's length.

High Score List: A list of the highest scores achieved by players is often displayed, encouraging competition and challenging players to beat previous records.

Obstacles: Some versions of the game introduce obstacles or barriers that the snake must avoid, adding an extra layer of challenge.

[
![snake game](https://github.com/Aman1-coder/GameSphere/assets/118098709/b2466095-91b7-483c-ae9c-6c08fd09c1fd)
](url)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by nikhilkumar50** [comment]
plz assign this game to me

**Comment by Aman1-coder** [comment]
@nikhilkumar50 Can you explain it is multiplayer game or not, if not so please try to create a multiplayer game I'll assign you 
If you need any help ask to mentor?
Connect with mentor:
LinkedIn : https://www.linkedin.com/in/durgeshkumar4993/
GitHub : https://github.com/Durgesh4993
