### ISSUE TITLE
Improvise readme.txt file. Correct spelling errors at various places and highlight important points for developers to notice easily

### ISSUE THREAD

**Issue by ArunMaramraj** [Aman1-coder/GameSphere#9]
Hello @Aman1-coder . Arun here and i'm a member of GSSOC '23. It is obvious that there are various use-cases and features of the project that might go unnoticed in the format that is given now. I want to help you in improvising the readme.txt file as it serves as an important start point for developers. I will correct the grammatical errors and present it in a way developers can understand the target features of project easily. Please assign me this task. Thank you!

**Comment by ArunMaramraj** [comment]
@Aman1-coder can you assign me this?

**Comment by shaileshthakur1** [comment]
@Aman1-coder I feel I have a good grip on the grammatical way of deliverables and have been writing for the google developer cloud community from the first year only, so I think I can work better on it. 

Can u assign me this issue?

**Comment by ArunMaramraj** [comment]
Hi @shaileshthakur1. I raised this issue yesterday. Im a contributor too. You need to write your own issues and get them assigned to you

**Comment by Aman1-coder** [comment]
@ArunMaramraj @shaileshthakur1 @S-ishita we are currently working on Home Page section so kindly please wait some time and also after passing one month then i'll change readme file currently not interested
