### ISSUE TITLE
[Bug]: Linking the Navigation bar items to their respective sections.

### ISSUE THREAD

**Issue by trishanu-init** [Aman1-coder/GameSphere#90]
### Give a brief about the bug ✍️

The internal links on the website(i.e. Home , Games , Tournament ,Contact etc.) do not link to their respective sections ,this will be a major issue if the website is pushed to production as it will hamper the User experience.

Assign me this issue under GSSoC'23 so that I can fix this bug.

### What is the expected behavior? 🤔

The Navigation items should link to their respective sections within the webpage

### Provide step by step information reproduce the bug 📄

- I will create individual sections for the following :
Homes
Games
Tournament
Join Community
Blogs
Contact Us
and assign the link to the sections to the navbar items

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@trishanu-init its already have been done. if you are able to make a multi player game in that case ill assign you.
