### ISSUE TITLE
Adding a scroll-to-top button 

### ISSUE THREAD

**Issue by deepeshgupta3257** [Aman1-coder/GameSphere#91]
### Describe your question or ask for support.❓

Adding a scroll-to-top button enables the user to scroll up the whole website in one click 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@deepeshgupta3257 its already have been done. if you are able to create a multi player game in that case ill think about to assign you.
