### ISSUE TITLE
Add: SIGN IN page

### ISSUE THREAD

**Issue by Pragati-3003** [Aman1-coder/GameSphere#99]
### Give a brief about the bug ✍️

Descriptions would like to add signing page for the better user interactions. 
So, please assign this issue to me under gssoc'23. 

### What is the expected behavior? 🤔

The sign in page will contain the user email and password. 

### Provide step by step information reproduce the bug 📄

I would like to make sign in page with data validation using JavaScript. 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Aman1-coder** [comment]
@Pragati-3003 Current we are try to find out those contributors who know about Web Sockets and we are current adding some multiplayer games
